package model;
// Generated Sep 26, 2024 8:29:42 PM by Hibernate Tools 4.3.1



/**
 * AdminDb generated by hbm2java
 */
public class AdminDb  implements java.io.Serializable {


     private Integer idAdmin;
     private String namaAdmin;
     private String username;
     private String password;

    public AdminDb() {
    }

    public AdminDb(String namaAdmin, String username, String password) {
       this.namaAdmin = namaAdmin;
       this.username = username;
       this.password = password;
    }
   
    public Integer getIdAdmin() {
        return this.idAdmin;
    }
    
    public void setIdAdmin(Integer idAdmin) {
        this.idAdmin = idAdmin;
    }
    public String getNamaAdmin() {
        return this.namaAdmin;
    }
    
    public void setNamaAdmin(String namaAdmin) {
        this.namaAdmin = namaAdmin;
    }
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }




}


