package model;
// Generated Sep 21, 2024 5:34:07 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Buku generated by hbm2java
 */
public class Buku  implements java.io.Serializable {


     private Integer idBuku;
     private byte[] gambarBuku;
     private String namaBuku;
     private Double hargaBuku;
     private String genreBuku;
     private String seriesBuku;
     private String deskripsiBuku;
     private Integer stockBuku;
     private Set<Orderitems> orderitemses = new HashSet<Orderitems>(0);
     private Set<Keranjang> keranjangs = new HashSet<Keranjang>(0);

    public Buku() {
    }

    public Buku(byte[] gambarBuku, String namaBuku, Double hargaBuku, String genreBuku, String seriesBuku, String deskripsiBuku, Integer stockBuku, Set<Orderitems> orderitemses, Set<Keranjang> keranjangs) {
       this.gambarBuku = gambarBuku;
       this.namaBuku = namaBuku;
       this.hargaBuku = hargaBuku;
       this.genreBuku = genreBuku;
       this.seriesBuku = seriesBuku;
       this.deskripsiBuku = deskripsiBuku;
       this.stockBuku = stockBuku;
       this.orderitemses = orderitemses;
       this.keranjangs = keranjangs;
    }
   
    public Integer getIdBuku() {
        return this.idBuku;
    }
    
    public void setIdBuku(Integer idBuku) {
        this.idBuku = idBuku;
    }
    public byte[] getGambarBuku() {
        return this.gambarBuku;
    }
    
    public void setGambarBuku(byte[] gambarBuku) {
        this.gambarBuku = gambarBuku;
    }
    public String getNamaBuku() {
        return this.namaBuku;
    }
    
    public void setNamaBuku(String namaBuku) {
        this.namaBuku = namaBuku;
    }
    public Double getHargaBuku() {
        return this.hargaBuku;
    }
    
    public void setHargaBuku(Double hargaBuku) {
        this.hargaBuku = hargaBuku;
    }
    public String getGenreBuku() {
        return this.genreBuku;
    }
    
    public void setGenreBuku(String genreBuku) {
        this.genreBuku = genreBuku;
    }
    public String getSeriesBuku() {
        return this.seriesBuku;
    }
    
    public void setSeriesBuku(String seriesBuku) {
        this.seriesBuku = seriesBuku;
    }
    public String getDeskripsiBuku() {
        return this.deskripsiBuku;
    }
    
    public void setDeskripsiBuku(String deskripsiBuku) {
        this.deskripsiBuku = deskripsiBuku;
    }
    public Integer getStockBuku() {
        return this.stockBuku;
    }
    
    public void setStockBuku(Integer stockBuku) {
        this.stockBuku = stockBuku;
    }
    public Set<Orderitems> getOrderitemses() {
        return this.orderitemses;
    }
    
    public void setOrderitemses(Set<Orderitems> orderitemses) {
        this.orderitemses = orderitemses;
    }
    public Set<Keranjang> getKeranjangs() {
        return this.keranjangs;
    }
    
    public void setKeranjangs(Set<Keranjang> keranjangs) {
        this.keranjangs = keranjangs;
    }




}


