package model;
// Generated Sep 21, 2024 5:34:07 PM by Hibernate Tools 4.3.1



/**
 * Keranjang generated by hbm2java
 */
public class Keranjang  implements java.io.Serializable {


     private Integer idKeranjang;
     private Buku buku;
     private UserDb userDb;
     private Integer totalBeli;

    public Keranjang() {
    }

    public Keranjang(Buku buku, UserDb userDb, Integer totalBeli) {
       this.buku = buku;
       this.userDb = userDb;
       this.totalBeli = totalBeli;
    }
   
    public Integer getIdKeranjang() {
        return this.idKeranjang;
    }
    
    public void setIdKeranjang(Integer idKeranjang) {
        this.idKeranjang = idKeranjang;
    }
    public Buku getBuku() {
        return this.buku;
    }
    
    public void setBuku(Buku buku) {
        this.buku = buku;
    }
    public UserDb getUserDb() {
        return this.userDb;
    }
    
    public void setUserDb(UserDb userDb) {
        this.userDb = userDb;
    }
    public Integer getTotalBeli() {
        return this.totalBeli;
    }
    
    public void setTotalBeli(Integer totalBeli) {
        this.totalBeli = totalBeli;
    }




}


