package model;
// Generated Sep 21, 2024 5:34:07 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Orders generated by hbm2java
 */
public class Orders  implements java.io.Serializable {


     private Integer orderId;
     private UserDb userDb;
     private String paymentMethod;
     private Double totalPrice;
     private Date orderDate;
     private String status;
     private String kodepembayaran;
     private byte[] buktiBayar;
     private Date expiryTime;
     private Boolean isStockReturned;
     private Set<Orderitems> orderitemses = new HashSet<Orderitems>(0);

    public Orders() {
    }

	
    public Orders(Date orderDate) {
        this.orderDate = orderDate;
    }
    public Orders(UserDb userDb, String paymentMethod, Double totalPrice, Date orderDate, String status, String kodepembayaran, byte[] buktiBayar, Date expiryTime, Boolean isStockReturned, Set<Orderitems> orderitemses) {
       this.userDb = userDb;
       this.paymentMethod = paymentMethod;
       this.totalPrice = totalPrice;
       this.orderDate = orderDate;
       this.status = status;
       this.kodepembayaran = kodepembayaran;
       this.buktiBayar = buktiBayar;
       this.expiryTime = expiryTime;
       this.isStockReturned = isStockReturned;
       this.orderitemses = orderitemses;
    }
   
    public Integer getOrderId() {
        return this.orderId;
    }
    
    public void setOrderId(Integer orderId) {
        this.orderId = orderId;
    }
    public UserDb getUserDb() {
        return this.userDb;
    }
    
    public void setUserDb(UserDb userDb) {
        this.userDb = userDb;
    }
    public String getPaymentMethod() {
        return this.paymentMethod;
    }
    
    public void setPaymentMethod(String paymentMethod) {
        this.paymentMethod = paymentMethod;
    }
    public Double getTotalPrice() {
        return this.totalPrice;
    }
    
    public void setTotalPrice(Double totalPrice) {
        this.totalPrice = totalPrice;
    }
    public Date getOrderDate() {
        return this.orderDate;
    }
    
    public void setOrderDate(Date orderDate) {
        this.orderDate = orderDate;
    }
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }
    public String getKodepembayaran() {
        return this.kodepembayaran;
    }
    
    public void setKodepembayaran(String kodepembayaran) {
        this.kodepembayaran = kodepembayaran;
    }
    public byte[] getBuktiBayar() {
        return this.buktiBayar;
    }
    
    public void setBuktiBayar(byte[] buktiBayar) {
        this.buktiBayar = buktiBayar;
    }
    public Date getExpiryTime() {
        return this.expiryTime;
    }
    
    public void setExpiryTime(Date expiryTime) {
        this.expiryTime = expiryTime;
    }
    public Boolean getIsStockReturned() {
        return this.isStockReturned;
    }
    
    public void setIsStockReturned(Boolean isStockReturned) {
        this.isStockReturned = isStockReturned;
    }
    public Set<Orderitems> getOrderitemses() {
        return this.orderitemses;
    }
    
    public void setOrderitemses(Set<Orderitems> orderitemses) {
        this.orderitemses = orderitemses;
    }




}


