package model;
// Generated Sep 26, 2024 8:29:42 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Orders generated by hbm2java
 */
public class Orders  implements java.io.Serializable {


     private Integer idOrder;
     private Buku buku;
     private UserDb userDb;
     private Date date;

    public Orders() {
    }

    public Orders(Buku buku, UserDb userDb, Date date) {
       this.buku = buku;
       this.userDb = userDb;
       this.date = date;
    }
   
    public Integer getIdOrder() {
        return this.idOrder;
    }
    
    public void setIdOrder(Integer idOrder) {
        this.idOrder = idOrder;
    }
    public Buku getBuku() {
        return this.buku;
    }
    
    public void setBuku(Buku buku) {
        this.buku = buku;
    }
    public UserDb getUserDb() {
        return this.userDb;
    }
    
    public void setUserDb(UserDb userDb) {
        this.userDb = userDb;
    }
    public Date getDate() {
        return this.date;
    }
    
    public void setDate(Date date) {
        this.date = date;
    }




}


