package model;
// Generated Sep 21, 2024 5:34:07 PM by Hibernate Tools 4.3.1



/**
 * Orderitems generated by hbm2java
 */
public class Orderitems  implements java.io.Serializable {


     private Integer orderItem;
     private Buku buku;
     private Orders orders;
     private Integer kuantitas;

    public Orderitems() {
    }

    public Orderitems(Buku buku, Orders orders, Integer kuantitas) {
       this.buku = buku;
       this.orders = orders;
       this.kuantitas = kuantitas;
    }
   
    public Integer getOrderItem() {
        return this.orderItem;
    }
    
    public void setOrderItem(Integer orderItem) {
        this.orderItem = orderItem;
    }
    public Buku getBuku() {
        return this.buku;
    }
    
    public void setBuku(Buku buku) {
        this.buku = buku;
    }
    public Orders getOrders() {
        return this.orders;
    }
    
    public void setOrders(Orders orders) {
        this.orders = orders;
    }
    public Integer getKuantitas() {
        return this.kuantitas;
    }
    
    public void setKuantitas(Integer kuantitas) {
        this.kuantitas = kuantitas;
    }




}


