package model;
// Generated Sep 28, 2024 11:48:54 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * PaymentMethod generated by hbm2java
 */
public class PaymentMethod  implements java.io.Serializable {


     private Integer idPayment;
     private String payment;
     private Set orderses = new HashSet(0);

    public PaymentMethod() {
    }

	
    public PaymentMethod(String payment) {
        this.payment = payment;
    }
    public PaymentMethod(String payment, Set orderses) {
       this.payment = payment;
       this.orderses = orderses;
    }
   
    public Integer getIdPayment() {
        return this.idPayment;
    }
    
    public void setIdPayment(Integer idPayment) {
        this.idPayment = idPayment;
    }
    public String getPayment() {
        return this.payment;
    }
    
    public void setPayment(String payment) {
        this.payment = payment;
    }
    public Set getOrderses() {
        return this.orderses;
    }
    
    public void setOrderses(Set orderses) {
        this.orderses = orderses;
    }




}


