package model;
// Generated Sep 27, 2024 8:16:42 PM by Hibernate Tools 4.3.1



/**
 * PaymentMethod generated by hbm2java
 */
public class PaymentMethod  implements java.io.Serializable {


     private Integer idPayment;
     private String payment;

    public PaymentMethod() {
    }

    public PaymentMethod(String payment) {
       this.payment = payment;
    }
   
    public Integer getIdPayment() {
        return this.idPayment;
    }
    
    public void setIdPayment(Integer idPayment) {
        this.idPayment = idPayment;
    }
    public String getPayment() {
        return this.payment;
    }
    
    public void setPayment(String payment) {
        this.payment = payment;
    }




}


