package model;
// Generated Sep 28, 2024 11:48:54 AM by Hibernate Tools 4.3.1



/**
 * UserAddress generated by hbm2java
 */
import javax.persistence.*;

@Entity
@Table(name="user_address")
public class UserAddress implements java.io.Serializable {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "id_address", unique = true, nullable = false)
    private Integer idAddress;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "user_id", nullable = false)
    private UserDb userDb;

    @Column(name = "address")
    private String address;

    @Column(name = "city")
    private String city;

    @Column(name = "postal_code")
    private String postalCode;

    public UserAddress() {
    }

    public UserAddress(UserDb userDb, String address, String city, String postalCode) {
       this.userDb = userDb;
       this.address = address;
       this.city = city;
       this.postalCode = postalCode;
    }
   
    public Integer getIdAddress() {
        return this.idAddress;
    }
    
    public void setIdAddress(Integer idAddress) {
        this.idAddress = idAddress;
    }
    public UserDb getUserDb() {
        return this.userDb;
    }
    
    public void setUserDb(UserDb userDb) {
        this.userDb = userDb;
    }
    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }
    public String getCity() {
        return this.city;
    }
    
    public void setCity(String city) {
        this.city = city;
    }
    public String getPostalCode() {
        return this.postalCode;
    }
    
    public void setPostalCode(String postalCode) {
        this.postalCode = postalCode;
    }




}


