package model;
// Generated Sep 27, 2024 8:16:42 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * UserDb generated by hbm2java
 */
public class UserDb  implements java.io.Serializable {


     private Integer idUser;
     private String namaUser;
     private String username;
     private String password;
     private String email;
     private Set orderses = new HashSet(0);
     private Set userAddresses = new HashSet(0);

    public UserDb() {
    }

    public UserDb(String namaUser, String username, String password, String email, Set orderses, Set userAddresses) {
       this.namaUser = namaUser;
       this.username = username;
       this.password = password;
       this.email = email;
       this.orderses = orderses;
       this.userAddresses = userAddresses;
    }
   
    public Integer getIdUser() {
        return this.idUser;
    }
    
    public void setIdUser(Integer idUser) {
        this.idUser = idUser;
    }
    public String getNamaUser() {
        return this.namaUser;
    }
    
    public void setNamaUser(String namaUser) {
        this.namaUser = namaUser;
    }
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public Set getOrderses() {
        return this.orderses;
    }
    
    public void setOrderses(Set orderses) {
        this.orderses = orderses;
    }
    public Set getUserAddresses() {
        return this.userAddresses;
    }
    
    public void setUserAddresses(Set userAddresses) {
        this.userAddresses = userAddresses;
    }




}


