package model;
// Generated Sep 26, 2024 8:29:42 PM by Hibernate Tools 4.3.1



/**
 * UserAddress generated by hbm2java
 */
public class UserAddress  implements java.io.Serializable {


     private Integer idAddress;
     private UserDb userDb;
     private String address;
     private String city;
     private String postalCode;

    public UserAddress() {
    }

    public UserAddress(UserDb userDb, String address, String city, String postalCode) {
       this.userDb = userDb;
       this.address = address;
       this.city = city;
       this.postalCode = postalCode;
    }
   
    public Integer getIdAddress() {
        return this.idAddress;
    }
    
    public void setIdAddress(Integer idAddress) {
        this.idAddress = idAddress;
    }
    public UserDb getUserDb() {
        return this.userDb;
    }
    
    public void setUserDb(UserDb userDb) {
        this.userDb = userDb;
    }
    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }
    public String getCity() {
        return this.city;
    }
    
    public void setCity(String city) {
        this.city = city;
    }
    public String getPostalCode() {
        return this.postalCode;
    }
    
    public void setPostalCode(String postalCode) {
        this.postalCode = postalCode;
    }




}


