package model;
// Generated Sep 28, 2024 11:48:54 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.*;


/**
 * UserDb generated by hbm2java
 */
@Entity
@Table(name="user_db")
public class UserDb implements java.io.Serializable {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "id_user", unique = true, nullable = false)
    private Integer idUser;

    @Column(name = "nama_user", nullable = false)
    private String namaUser;

    @Column(name = "username", nullable = false)
    private String username;

    @Column(name = "password", nullable = false)
    private String password;

    @Column(name = "email", nullable = false)
    private String email;

    
     private Set orderses = new HashSet(0);
     
     @OneToMany(fetch = FetchType.LAZY, mappedBy = "userDb")
    private Set<UserAddress> userAddresses = new HashSet<>(0);

    public UserDb() {
    }

    public UserDb(String namaUser, String username, String password, String email, Set orderses, Set userAddresses) {
       this.namaUser = namaUser;
       this.username = username;
       this.password = password;
       this.email = email;
       this.orderses = orderses;
       this.userAddresses = userAddresses;
    }
   
    public Integer getIdUser() {
        return this.idUser;
    }
    
    public void setIdUser(Integer idUser) {
        this.idUser = idUser;
    }
    public String getNamaUser() {
        return this.namaUser;
    }
    
    public void setNamaUser(String namaUser) {
        this.namaUser = namaUser;
    }
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public Set getOrderses() {
        return this.orderses;
    }
    
    public void setOrderses(Set orderses) {
        this.orderses = orderses;
    }
    public Set getUserAddresses() {
        return this.userAddresses;
    }
    
    public void setUserAddresses(Set userAddresses) {
        this.userAddresses = userAddresses;
    }




}