package model;
// Generated Sep 21, 2024 5:34:07 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * UserDb generated by hbm2java
 */
public class UserDb  implements java.io.Serializable {


     private Integer idUser;
     private String namaUser;
     private String username;
     private String password;
     private String email;
     private Set<Keranjang> keranjangs = new HashSet<Keranjang>(0);
     private Set<Orders> orderses = new HashSet<Orders>(0);
     private Set<UserAddress> userAddresses = new HashSet<UserAddress>(0);

    public UserDb() {
    }

    public UserDb(String namaUser, String username, String password, String email, Set<Keranjang> keranjangs, Set<Orders> orderses, Set<UserAddress> userAddresses) {
       this.namaUser = namaUser;
       this.username = username;
       this.password = password;
       this.email = email;
       this.keranjangs = keranjangs;
       this.orderses = orderses;
       this.userAddresses = userAddresses;
    }
   
    public Integer getIdUser() {
        return this.idUser;
    }
    
    public void setIdUser(Integer idUser) {
        this.idUser = idUser;
    }
    public String getNamaUser() {
        return this.namaUser;
    }
    
    public void setNamaUser(String namaUser) {
        this.namaUser = namaUser;
    }
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public Set<Keranjang> getKeranjangs() {
        return this.keranjangs;
    }
    
    public void setKeranjangs(Set<Keranjang> keranjangs) {
        this.keranjangs = keranjangs;
    }
    public Set<Orders> getOrderses() {
        return this.orderses;
    }
    
    public void setOrderses(Set<Orders> orderses) {
        this.orderses = orderses;
    }
    public Set<UserAddress> getUserAddresses() {
        return this.userAddresses;
    }
    
    public void setUserAddresses(Set<UserAddress> userAddresses) {
        this.userAddresses = userAddresses;
    }




}


